// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUUI1tA7GLyX9YIv6OsVaQe21NYwjrue0',
    appId: '1:543019960746:web:726ad404070c37d45b43d3',
    messagingSenderId: '543019960746',
    projectId: 'daletrasufape',
    authDomain: 'daletrasufape.firebaseapp.com',
    storageBucket: 'daletrasufape.appspot.com',
    measurementId: 'G-2PCKML1Z2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2HVpv-HmBfJ4iaVvJg82gym9dO8fEiaU',
    appId: '1:543019960746:android:fcb1c41ada80dff25b43d3',
    messagingSenderId: '543019960746',
    projectId: 'daletrasufape',
    storageBucket: 'daletrasufape.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2btRhkJlB2AQMVLFTDTo3xboQTfTINNo',
    appId: '1:543019960746:ios:d2def42c205c1ad45b43d3',
    messagingSenderId: '543019960746',
    projectId: 'daletrasufape',
    storageBucket: 'daletrasufape.appspot.com',
    iosClientId: '543019960746-g4nrj8c9aeai3o4i65bmv87v71826dgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.thunderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2btRhkJlB2AQMVLFTDTo3xboQTfTINNo',
    appId: '1:543019960746:ios:d2def42c205c1ad45b43d3',
    messagingSenderId: '543019960746',
    projectId: 'daletrasufape',
    storageBucket: 'daletrasufape.appspot.com',
    iosClientId: '543019960746-g4nrj8c9aeai3o4i65bmv87v71826dgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.thunderapp',
  );
}
